In [20]:
import numpy as np
import psycopg2
import pandas as pd

In [100]:
conn = psycopg2.connect(dbname="postgres", user="postgres", password="1234", host="127.0.0.1", port="5432")

pd.read_sql("SELECT * FROM transactions", con=conn)

/var/folders/gm/k7zht6d94tsg4c528f08wpvc0000gn/T/ipykernel_42068/2428872032.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM transactions", con=conn)

    transaction_id  user_id  amount currency          event_time
0                1        1   100.0      EUR 2024-01-01 10:15:00
1                2        1    50.0      EUR 2024-01-02 11:00:00
2                3        2   200.0      EUR 2024-01-02 12:30:00
3                4        3   150.0      EUR 2024-01-03 09:45:00
4                5        3   -20.0      EUR 2024-01-04 13:20:00
5                6        4   300.0      EUR 2024-01-05 16:10:00
6                7        5   120.0      EUR 2024-01-06 08:05:00
7                4        3   150.0      EUR 2024-01-03 09:45:00
8                2        1    50.0      EUR 2024-01-02 11:00:00
9                8        1    70.0      EUR 2024-01-07 10:00:00
10               9        1    30.0      EUR 2024-01-08 12:00:00
11              10        2    90.0      EUR 2024-01-09 14:00:00

In [98]:
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://postgres:1234@127.0.0.1:5432/postgres"
engine = create_engine(DATABASE_URL)

In [99]:
with engine.connect() as conn:
    df = pd.read_sql("SELECT * FROM transactions", con=conn)

df

    transaction_id  user_id  amount currency          event_time
0                1        1   100.0      EUR 2024-01-01 10:15:00
1                2        1    50.0      EUR 2024-01-02 11:00:00
2                3        2   200.0      EUR 2024-01-02 12:30:00
3                4        3   150.0      EUR 2024-01-03 09:45:00
4                5        3   -20.0      EUR 2024-01-04 13:20:00
5                6        4   300.0      EUR 2024-01-05 16:10:00
6                7        5   120.0      EUR 2024-01-06 08:05:00
7                4        3   150.0      EUR 2024-01-03 09:45:00
8                2        1    50.0      EUR 2024-01-02 11:00:00
9                8        1    70.0      EUR 2024-01-07 10:00:00
10               9        1    30.0      EUR 2024-01-08 12:00:00
11              10        2    90.0      EUR 2024-01-09 14:00:00

In [101]:
n = 1_000_000
syn_df = pd.DataFrame({
        "transaction_id": range(1, n + 1),
        "user_id": np.random.choice(range(100), n),
        "amount": np.round(np.random.uniform(5, 500, size=n), 2),
        "currency": np.random.choice(['EUR', 'USD', 'RUB'], n),
        "event_time": pd.to_datetime("2023-01-01") + pd.to_timedelta(np.random.randint(0, 800, n), unit="D"),
    })

In [103]:
%%time

with engine.connect() as conn:
    syn_df.to_sql(name='medium_transactions', con=conn)

CPU times: user 7.6 s, sys: 383 ms, total: 7.98 s
Wall time: 12.6 s

In [81]:
%%time

conn = psycopg2.connect(dbname="postgres", user="postgres", password="1234", host="127.0.0.1", port="5432")
cursor = conn.cursor()

cursor.execute("""create table public.medium_transactions_cursor(
        transaction_id INTEGER,
        user_id INTEGER,
        amount NUMERIC,
        currency TEXT,
        event_time TIMESTAMP
    )""")

cols = ','.join(list(syn_df.columns))
tpls = [tuple([x[0], x[1], x[2], x[3], str(x[4])]) for x in syn_df.to_numpy()]

sql = "INSERT INTO public.medium_transactions_cursor({}) VALUES(%s, %s, %s, %s, %s)".format(cols)

cursor.executemany(sql, tpls)

conn.commit()

CPU times: user 681 ms, sys: 837 ms, total: 1.52 s
Wall time: 12.1 s

In [104]:
%%timeit

with engine.connect() as conn:
    result_df = pd.read_sql('select * from medium_transactions where user_id = 10', con=conn)

23 ms ± 431 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [105]:
%%timeit

with engine.connect() as conn:
    result_df = pd.read_sql('select * from medium_transactions where user_id = 10', con=conn)

16.4 ms ± 936 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [106]:
%%time

with engine.connect() as conn:
    syn_df.to_sql(name='medium_transactions_part', con=conn, if_exists='append', index=False)

CPU times: user 6.48 s, sys: 197 ms, total: 6.67 s
Wall time: 8.95 s

In [107]:
%%timeit

with engine.connect() as conn:
    result_df = pd.read_sql('select * from medium_transactions_part where user_id = 10', con=conn)

15.9 ms ± 226 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)